-- Sample documents for testing
-- Note: These are sample entries - in production, you would have actual file paths and content

INSERT INTO documents (title, filename, file_path, content_text, file_size, mime_type) VALUES
(
    'Introduction to Machine Learning',
    'ml_intro.pdf',
    'storage/uploads/sample_ml_intro.pdf',
    'Machine learning is a subset of artificial intelligence (AI) that provides systems the ability to automatically learn and improve from experience without being explicitly programmed. Machine learning focuses on the development of computer programs that can access data and use it to learn for themselves. The process of learning begins with observations or data, such as examples, direct experience, or instruction, in order to look for patterns in data and make better decisions in the future based on the examples that we provide. The primary aim is to allow the computers learn automatically without human intervention or assistance and adjust actions accordingly.',
    1024000,
    'application/pdf'
),
(
    'Database Design Principles',
    'database_design.txt',
    'storage/uploads/sample_database_design.txt',
    'Database design is the organization of data according to a database model. The designer determines what data must be stored and how the data elements interrelate. With this information, they can begin to fit the data to the database model. Database design involves classifying data and identifying interrelationships. This theoretical representation of the data is called a data model. The data model is an abstract model that organizes elements of data and standardizes how they relate to one another and to the properties of real-world entities.',
    512000,
    'text/plain'
),
(
    'Web Security Best Practices',
    'web_security.pdf',
    'storage/uploads/sample_web_security.pdf',
    'Web application security is a branch of information security that deals specifically with security of websites, web applications and web services. At a high level, web application security draws on the principles of application security but applies them specifically to internet and web systems. Web security vulnerabilities include cross-site scripting (XSS), SQL injection, cross-site request forgery (CSRF), and many others. Implementing proper security measures is crucial for protecting sensitive data and maintaining user trust.',
    768000,
    'application/pdf'
),
(
    'Project Management Methodologies',
    'pm_methodologies.txt',
    'storage/uploads/sample_pm_methodologies.txt',
    'Project management methodologies are essentially different ways to approach a project. There are many methodologies available, and each has its own strengths and weaknesses. Some popular methodologies include Waterfall, Agile, Scrum, Kanban, and Lean. The Waterfall methodology is a linear approach where each phase must be completed before the next one begins. Agile methodology, on the other hand, is iterative and allows for changes throughout the project lifecycle. Choosing the right methodology depends on various factors including project size, complexity, team experience, and client requirements.',
    640000,
    'text/plain'
),
(
    'Cloud Computing Architecture',
    'cloud_architecture.pdf',
    'storage/uploads/sample_cloud_architecture.pdf',
    'Cloud computing architecture refers to the components and subcomponents required for cloud computing. These components typically consist of a front end platform, back end platforms, a cloud based delivery, and a network. Combined, these components make up cloud computing architecture. Cloud computing architecture is divided into two main categories: front-end architecture and back-end architecture. The front-end architecture includes the user interface and the client-side applications that are used to access the cloud computing services. The back-end architecture includes the servers, storage systems, virtual machines, and other resources that provide the cloud computing services.',
    896000,
    'application/pdf'
);

-- Sample search cache entries (these would normally be generated by actual searches)
INSERT INTO search_cache (query_hash, query_text, results, expires_at) VALUES
(
    MD5('machine learning'),
    'machine learning',
    '{"data": [{"id": 1, "title": "Introduction to Machine Learning", "relevance_score": 0.95}], "pagination": {"total": 1}}',
    DATE_ADD(NOW(), INTERVAL 1 HOUR)
),
(
    MD5('database'),
    'database',
    '{"data": [{"id": 2, "title": "Database Design Principles", "relevance_score": 0.87}], "pagination": {"total": 1}}',
    DATE_ADD(NOW(), INTERVAL 1 HOUR)
),
(
    MD5('security'),
    'security',
    '{"data": [{"id": 3, "title": "Web Security Best Practices", "relevance_score": 0.92}], "pagination": {"total": 1}}',
    DATE_ADD(NOW(), INTERVAL 1 HOUR)
);